Implement as_steps in profile layer state
glue-viz/glue pull request #2292
Opened 2022-04-19 15:15 UTC by kecnry

## Description

This implements a new boolean switch in the profile layer state to toggle displaying the profile as steps vs a line plot.  ~The actual binning logic is adopted from https://github.com/astropy/specutils/blob/main/specutils/spectra/spectral_axis.py#L42.~ (binning logic has now been moved to the bqplot artist in glue-viz/glue-jupyter#309)

2022-04-19 15:20 UTC, maartenbreddels commented
Nice, I didn't expect it to be as simple, LGTM, also [#309](https://github.com/glue-viz/glue-jupyter/pull/309)

2022-04-19 15:49 UTC, astrofrog commented
As mentioned on Slack, I don't think we want to make these changes here - the Matplotlib viewers already draw things as steps by default so it is really the bqplot layer artist in glue-jupyter which should be updated to include this kind of logic.

If we do want to support the option of having both draw styles, then I do support adding a drawstyle or as_steps option to the state, but it should then default to True and simply toggle the drawstyle in the Matplotlib viewer, and again the logic for glue-jupyter should live specifically in the bqplot layer artist (since the Matplotlib layer artist will be taken from glue-core and already draw as steps).

2022-04-22 11:16 UTC, astrofrog requested changes
Looks good! Just a small comment below about removing unused code.

2022-04-22 11:16 UTC, astrofrog commented on glue/viewers/profile/state.py
> +        #self.add_callback('as_steps', self._on_as_steps_change, priority=1000)
Remove if unused?

2022-04-22 11:20 UTC, astrofrog commented
Can you also fix the codestyle failure (run ``tox -e codestyle`` locally to check) and add a changlog entry?

2022-04-22 15:54 UTC, astrofrog approved these changes

2022-04-22 15:54 UTC, merged