Apply foreground color to minor ticks
glue-viz/glue pull request #2305
Opened 2022-05-31 23:05 UTC by Carifio24

There is currently a bug where any minor ticks displayed will not match the user's global settings. (Note that this isn't an issue with the default settings, since the labels are black either way.) One prominent example is the scientific notation tick marks that are sometimes used when displaying an axis in log mode. See below for an example:

![log-label-colors](https://user-images.githubusercontent.com/14281631/171296270-548958ce-0e7b-4b72-8627-283437637cef.png)

This occurs because we only set major tick labels to match the given color in `set_foreground_color` (see the matplotlib documentation [here](https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.axes.Axes.tick_params.html#matplotlib.axes.Axes.tick_params); the default value for `which` is `"major"`). This PR fixes the issue by setting `which="both"`).

2022-08-04 13:46 UTC, astrofrog requested changes

2022-08-04 13:46 UTC, astrofrog commented on CHANGES.md
> +* Fixed a bug where minor tick marks were not respecting the settings colors. [#2305]
Can you move this to 1.6.0? (I am going to work on a way to avoid us having to do this in future)

2022-08-05 00:40 UTC, Carifio24 commented
@astrofrog I've rebased and moved the changelog entry to the 1.6.0 section.

2022-08-05 10:53 UTC, astrofrog commented
Could you check the codestyle failure with ``tox -e codestyle`` - thanks!

2022-08-05 11:03 UTC, Carifio24 commented
Hmm - it looks like the codestyle failure is actually coming from the main branch. Taking a quick look there, the codestyle check went from succeeding to failing after #2300 was merged - although codestyle passed in that PR and didn't change any of the offending files. I think the culprit is the E275 update described [here](https://pycodestyle.pycqa.org/en/latest/developer.html#changes).

2022-08-05 13:26 UTC, astrofrog approved these changes

2022-08-05 13:27 UTC, merged

2022-08-08 17:07 UTC, dhomeier commented
> any of the offending files. I think the culprit is the E275 update described [here](https://pycodestyle.pycqa.org/en/latest/developer.html#changes).

Thanks for identifying this @Carifio24 . The codestyle is fixed in #2308 now.