Add filter/search to table viewer
glue-viz/glue pull request #2392
Opened 2023-04-26 19:33 UTC by jfoster17

# Add filter/search to the Table Viewer

![table_filter](https://user-images.githubusercontent.com/3639698/234683280-b4ca2b5d-0c14-48db-8d9b-fd36cc08d646.gif)

## Description

This PR adds a search/filter field and component selection widget to the Table Viewer. The displayed elements in the table are then filtered based on applying `re.search()` to the selected component. The primary motivation is to allow the user to use the GUI to find matching rows in a dataset and create a subset from those rows. I limit the user to searching on categorical components.

This necessitated adding a TableViewerState in order to keep track of the things going into the filter. 

I experimented with using `QSortFilterProxyModel` just for the filtering and although I was able to get a working implementation, I was then getting frequent segfaults that I was unable to diagnose. Since we are already doing sort within our custom `DataTableModel` it was easy enough to apply the filtering here as well. (I also that using `QSortFilterProxyModel` was rejected in b7a0f67500 for performance concerns, but performance seemed okay for the filtering component).

Still to do:

- [ ] Save/restore tests are failing
- [ ] Add tests specific to the filtering

Closes #2386

2023-04-27 11:01 UTC, astrofrog commented
Very nice! Let me know once you would like me to review this :) One request is whether we could hide the search box by default and have a viewer tool with a 'funnel' icon for filtering that when clicked would toggle the search box?

2023-04-27 13:18 UTC, jfoster17 commented
> Very nice! Let me know once you would like me to review this :) One request is whether we could hide the search box by default and have a viewer tool with a 'funnel' icon for filtering that when clicked would toggle the search box?

I considered that. I think that it is better to have the search box by default because 

1. It does not take up that much space
2. The "default" reason to open up a Table Viewer is to identify specific rows (perhaps the most common reason is actually to get a look at your dataset, but finding specific items is probably the second most common reason)

Thus I think the friction of requiring a user to correctly identify and toggle the 'funnel' item for the most common interaction with a table is not worth the marginal cost of having a little bit less space in the viewer for showing the data.

2023-04-27 19:26 UTC, jfoster17 commented
@astrofrog -- this is ready for your review.

I presented at our glue weekly meeting and they were fine with having the search bar be shown all the time. The main request was to be able to toggle the regex search so that users won't be tripped up if they want to search for unescaped special characters; I have now added this button.

2023-05-12 09:02 UTC, astrofrog requested changes
Looks great! Just a few small things

2023-05-12 09:02 UTC, astrofrog commented on glue/viewers/table/qt/data_viewer.py
> +        self._connection3 = connect_checkable_button(self.state, 'regex', self.ui.bool_regex)
You could perhaps use autoconnect here like we do in a lot of the other widgets?

2023-05-12 09:02 UTC, astrofrog commented on glue/viewers/table/compat.py
> +        properties = rec.pop('properties')
If we don't use this, maybe best to write as ``_ = rec.pop(...)``

2023-05-12 09:02 UTC, astrofrog commented on glue/viewers/table/qt/data_viewer.py
> +        self._connection3 = connect_checkable_button(self.state, 'regex', self.ui.bool_regex)
See https://echo.readthedocs.io/en/latest/api/echo.qt.autoconnect_callbacks_to_qt.html#echo.qt.autoconnect_callbacks_to_qt for more info

2023-05-15 10:01 UTC, astrofrog approved these changes
Looks great, thanks!

2023-05-15 10:01 UTC, merged