FEAT: New CircularAnnulusROI class to represent circular annulus ROI
glue-viz/glue pull request #2403
Opened 2023-05-11 20:43 UTC by pllim

This PR adds a new class to represent circular annulus as ROI.

Motivation: Even though we can use annulus now after https://github.com/glue-viz/glue-astronomy/pull/90 , it is not very user-friendly, as we have to expose parameters from the outer and inner circles separately, which would cause user to easily make the subset state no longer a circular annulus (see https://github.com/spacetelescope/jdaviz/pull/2182#issuecomment-1542882590 for exciting screenshots). Therefore, there is a need to represent this shape as ROI so that we only expose the relevant parameters (one center only, inner radius, outer radius) without a lot of hacky workaround downstream.

With this patch, I could do the following in Jdaviz after unpinning maxversion of glue-core (xref https://github.com/spacetelescope/jdaviz/issues/2183).

```diff
--- a/pyproject.toml
+++ b/pyproject.toml
@@ -12,7 +12,7 @@ dependencies = [
     "traitlets>=5.0.5",
     "bqplot>=0.12.37",
     "bqplot-image-gl>=1.4.11",
-    "glue-core>=1.6.0,!=1.9.0,<1.10",
+    "glue-core>=1.6.0,!=1.9.0",
     "glue-jupyter>=0.15.0",
     "echo>=0.5.0",
     "ipykernel>=6.19.4",
```

```python
import numpy as np
from glue.core.roi import CircularAnnulusROI
from glue.core.subset import RoiSubsetState

from jdaviz import Imviz

a = np.arange(100).reshape((10, 10))

imviz = Imviz()
imviz.load_data(a, data_label='a')
imviz.show()

ann = CircularAnnulusROI(xc=10, yc=10, inner_radius=5, outer_radius=8)
sbst = RoiSubsetState(xatt=data_image.pixel_component_ids[1], yatt=data_image.pixel_component_ids[0], roi=ann)
app.data_collection.new_subset_group(subset_state=sbst)
```

![Screenshot 2023-05-11 162530](https://github.com/glue-viz/glue/assets/2090236/24d54af5-ff5c-4ff5-9b82-5efca7a3f9da)

The next step following this PR is to support this new ROI both in glue-astronomy and Jdaviz.

2023-05-12 09:09 UTC, astrofrog requested changes
Looks good to me! I think it would be better to implement something for the polygon though, have left a comment below.

2023-05-12 09:09 UTC, astrofrog commented on glue/core/roi.py
> +        raise NotImplementedError("Cannot transform annulus to simple polygon")
Maybe better than nothing would be to transform it to a polygon like this:

<img width="428" alt="Screenshot 2023-05-12 at 10 05 18" src="https://github.com/glue-viz/glue/assets/314716/c2232a87-01e1-4aa0-8fa4-7b046a073f09">

I've exaggerated the separation of the lines at the top, these could be actually over each other if you see what I mean. Does this make sense?

2023-05-12 13:29 UTC, pllim commented
Using the example posted above, this is what the polygon looks like:

```python
from matplotlib import pyplot as plt

x, y = ann.to_polygon()

plt.gca().set_aspect('equal')
plt.plot(x, y)
```

![annulus_poly](https://github.com/glue-viz/glue/assets/2090236/9d0f087e-8a57-4de5-b4a5-9a3638b881c5)

2023-05-12 13:36 UTC, astrofrog commented
Great! Maybe we should have 100 points instead of 20?

2023-05-12 14:10 UTC, pllim commented
Done!

![ann_poly_100](https://github.com/glue-viz/glue/assets/2090236/987985a0-1743-4964-baf7-1e8d43bf090d)

2023-05-12 14:13 UTC, pllim commented
Not sure why CI didn't kick off.

2023-05-15 09:57 UTC, astrofrog approved these changes
Looks great, thanks!

2023-05-15 09:57 UTC, merged