Remove python 38 and 39 from min python
glue-viz/glue pull request #2514
Opened 2024-09-17 09:03 UTC by CyclingNinja

Removes old python versions from builds and min required python

2024-09-17 09:56 UTC, astrofrog requested changes
Small comment below - also could you check whether the documentation needs updating in the installation instructions? (regarding the minimum version of Python)

2024-09-17 09:56 UTC, astrofrog commented on setup.cfg
>      Programming Language :: Python :: 3.9
Could you remove 3.8 and 3.9 here?

2024-09-17 10:52 UTC, astrofrog approved these changes
Thanks! I reworded the title just as this gets used for the user-facing change notes

2024-09-17 10:52 UTC, merged

2024-09-17 15:41 UTC, dhomeier commented on setup.cfg
>      Programming Language :: Python :: 3.9
These have been forgotten

2024-09-17 15:57 UTC, dhomeier commented
A bit puzzled why `py310-test-dev` is still running here, but not for `glue-qt` – is `astropy>=0.0.dev0` resolved differently from `git+https://github.com/astropy/astropy` (weekly wheels or something)?
Either way this may still start to fail here as well once the former are updated to astropy HEAD.
Also does the LTS test need no replacement?

2024-09-23 20:03 UTC, dhomeier commented
> Either way this may still start to fail here as well once the former are updated to astropy HEAD.

@astrofrog, @CyclingNinja, `astropy>=0.0.dev0` is now getting `astropy==6.1.3` installed on `py310-test-dev`, so one dev test should probably be pushed to py312.